version: '3.3'

services:
  webm-to-mpx-node:
    build: .
    env_file: .env
    restart: on-failure
    ports:
      - 3001:3001
    volumes:
      - ./src_node:/app
    working_dir: '/app'
    command: 'node index.js'

    # webm-to-mpx-go:
    #  build: .
    #  env_file: .env
    #  restart: on-failure
    #  ports:
    #    - 3001:3001
    #  volumes:
    #    - ./src_go:/app
    #  working_dir: '/app'
    #  command: "go run main.go"
